INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 1", "game", 5000, "1/1/2017", "12/31/2017");
INSERT INTO users (name, age) VALUES ("User 1", 23);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 12, 3);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 2", "clothes", 50000, "1/1/2017", "12/31/2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 3", "website", 10000, "1/1/2017", "12/31/2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 4", "tech", 15000, "1/1/2017", "12/31/2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 5", "kitchen", 25000, "1/1/2017", "12/31/2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 6", "pets", 50000, "1/1/2017", "12/31/2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 7", "game", 75000, "1/1/2017", "12/31/2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 8", "kitchen", 35000, "1/1/2017", "12/31/2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 9", "pets", 15000, "1/1/2017", "12/31/2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 10", "pets", 5000, "1/1/2017", "12/31/2017");

INSERT INTO users (name, age) VALUES ("User 2", 23);
INSERT INTO users (name, age) VALUES ("User 3", 45);
INSERT INTO users (name, age) VALUES ("User 4", 24);
INSERT INTO users (name, age) VALUES ("User 5", 44);
INSERT INTO users (name, age) VALUES ("User 6", 25);
INSERT INTO users (name, age) VALUES ("User 7", 43);
INSERT INTO users (name, age) VALUES ("User 8", 26);
INSERT INTO users (name, age) VALUES ("User 9", 42);
INSERT INTO users (name, age) VALUES ("User 10", 27);
INSERT INTO users (name, age) VALUES ("User 11", 41);
INSERT INTO users (name, age) VALUES ("User 12", 28);
INSERT INTO users (name, age) VALUES ("User 13", 40);
INSERT INTO users (name, age) VALUES ("User 14", 29);
INSERT INTO users (name, age) VALUES ("User 15", 39);
INSERT INTO users (name, age) VALUES ("User 16", 30);
INSERT INTO users (name, age) VALUES ("User 17", 38);
INSERT INTO users (name, age) VALUES ("User 18", 31);
INSERT INTO users (name, age) VALUES ("User 19", 27);
INSERT INTO users (name, age) VALUES ("User 20", 32);

INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 3);
